import requests
import os

BASE_URL = "http://127.0.0.1:5000"

def upload_pdf():
    pdf_path = input("Enter full path to PDF: ").strip()
    if not os.path.exists(pdf_path):
        print(" File not found:", pdf_path)
        return None

    print("\n Uploading PDF ")
    with open(pdf_path, "rb") as f:
        response = requests.post(f"{BASE_URL}/upload/", files={"file": f})
    print(" Upload Response:", response.json())
    return response.json()

def query_doc():
    question = input("\nEnter your question: ").strip()
    print("\n Querying Document ")
    response = requests.post(f"{BASE_URL}/query/", json={"question": question})
    data = response.json()
    print("\n Answer:", data.get("answer"))
    print("\n Key Points:")
    for point in data.get("bullet_points", []):
        print("-", point)
    print("\n Test Question:", data.get("test_question"))
    return data

def evaluate(test_question_id):
    user_answer = input("\nEnter your answer (A/B/C/D): ").strip().upper()
    print("\n Evaluating Answer ")
    response = requests.post(f"{BASE_URL}/evaluate/", json={
        "test_question_id": test_question_id,
        "user_answer": user_answer
    })
    print("\n Evaluation:", response.json())
    return response.json()

if __name__ == "__main__":
    # It Upload PDF
    upload_pdf()

    # Now ask A question
    qa_response = query_doc()

    # Answer test question generated by our system
    if qa_response and "test_question_id" in qa_response:
        evaluate(qa_response["test_question_id"])
